/**
 * config.ts — Verifier App configuration.
 * ============================================================================
 * WHY THE PLATFORM PUBLIC KEY IS HARDCODED HERE (and why that's correct):
 * ============================================================================
 * This is the app's anchor of trust (Frozen Spec §4.2, §16). A public key is
 * — by definition — safe to embed in distributed, reverse-engineerable
 * client code; the whole point of public-key cryptography is that the
 * public half provides no help in forging a signature. Hardcoding it here
 * means a compromised backend (Frozen Spec §1's threat model) cannot swap
 * out which key the app trusts — the app carries its own copy, baked in at
 * build time, independent of anything the network ever tells it.
 *
 * THE VALUE BELOW is the sample/demo platform key generated by
 * `offline-signer keygen` and stored in /samples/platform-key.json
 * (publicKeyHex field) for this bundled demo. In a real deployment, replace
 * this with YOUR OWN platform trust key's public half, generated on an
 * offline machine — never reuse this demo key for anything beyond trying
 * out this project.
 */

import Constants from 'expo-constants';

/**
 * The backend's base URL.
 * ============================================================================
 * WHY THIS IS NOT SIMPLY 'http://localhost:4000':
 * ============================================================================
 * On a physical phone running Expo Go, `localhost` refers to the PHONE
 * itself — there is no backend listening on the phone, so every request
 * fails with a network error, even though the backend is running perfectly
 * fine on the developer's computer. (On some Android emulators `localhost`
 * happens to get remapped to the host machine, which is why this problem
 * doesn't always show up in every testing setup — but it always fails on a
 * real device, which is the common case.)
 *
 * The fix: derive the developer machine's LAN IP address from the Metro
 * bundler's own connection info. When the app is running via `expo start`
 * (Expo Go or a dev client), `Constants.expoConfig.hostUri` is populated
 * with exactly the address the phone already used to download this app's
 * JS bundle — e.g. "192.168.1.5:8081". That's guaranteed to be an address
 * the phone can actually reach, since it just used it. We reuse the IP part
 * and swap in the backend's own port.
 *
 * In a standalone/production build (no Metro dev server, so `hostUri` is
 * undefined), this falls back to PRODUCTION_API_BASE_URL below — set that
 * to your real deployed backend's URL before building for production.
 */
const PRODUCTION_API_BASE_URL = 'https://your-deployed-backend.example.com';
const BACKEND_PORT = 4000;

function resolveApiBaseUrl(): string {
  const hostUri = Constants.expoConfig?.hostUri;
  if (hostUri) {
    const host = hostUri.split(':')[0];
    if (host && host !== 'localhost' && host !== '127.0.0.1') {
      return `http://${host}:${BACKEND_PORT}`;
    }
  }
  return PRODUCTION_API_BASE_URL;
}

export const API_BASE_URL = resolveApiBaseUrl();

/**
 * The platform trust key's public half (Frozen Spec §4.2, §8). Every
 * Trust Manifest fetched from the backend must carry a signature that
 * verifies against this exact value — if it doesn't, Engine 1 rejects the
 * manifest outright (Frozen Spec §14, step 2), regardless of what the
 * (untrusted) backend claims.
 */
export const PLATFORM_PUBLIC_KEY_HEX = 'ae4aff432dce61e90c42ad1d5a8a6dbfe901dc860bc26d71e2c4a63624d7b929';

/**
 * How long (in milliseconds) a request to the backend is allowed to hang
 * before Engine 1 treats it as a network failure (Frozen Spec §15,
 * NETWORK_ERROR) rather than waiting indefinitely.
 */
export const REQUEST_TIMEOUT_MS = 8000;

/**
 * How long POST /v2/verify/:docId (Engine 2's forensic pipeline: image
 * alignment, multilingual OCR, template/asset matching) is allowed to
 * run before the app gives up and shows a network-error state. Deliberately
 * much longer than REQUEST_TIMEOUT_MS above — Engine 2 does real
 * image-processing work server-side, unlike the lightweight
 * manifest/credential GETs, and a large document photo also simply takes
 * longer to upload than a QR payload does.
 */
export const ENGINE2_REQUEST_TIMEOUT_MS = 30000;

/** AsyncStorage key used to persist the highest Trust Manifest version ever seen (rollback defense, Frozen Spec §14 step 3). */
export const MANIFEST_VERSION_STORAGE_KEY = 'trustanchor_highest_manifest_version';