/**
 * D:\JUNE2026TESTING\packages\backend\src\services\qr.ts
 * qr.ts — server-side QR generation for batch PDF rendering.
 * ============================================================================
 * WHY THIS DUPLICATES A SLICE OF offline-signer/src/generateQr.ts RATHER
 * THAN IMPORTING IT: offline-signer is conceptually an OFFLINE-only tool
 * (Frozen Spec §5) — nothing about this file changes that, since QR
 * rendering never touches a private key (it only encodes an ALREADY-
 * COMPUTED hash+signature pair that a signed batch upload already carries),
 * but keeping the two packages' dependency graphs completely separate
 * avoids any future temptation to import something signing-related across
 * that boundary. The actual encoding logic below is intentionally
 * byte-for-byte identical to generateQr.ts's — same CBOR payload shape,
 * same base64-text convention — so a PDF generated here scans exactly like
 * one generated by the offline CLI.
 */
import QRCode from 'qrcode';
import { encodeQrPayload, uuidToBytes, QrPayload } from '@trustanchor/shared';

export interface BuildQrInput {
  issuerId: string;
  docId: string;
  contentHashHex: string;
  signatureHex: string;
}

export function buildQrBytes(input: BuildQrInput): Buffer {
  const h = Buffer.from(input.contentHashHex, 'hex');
  const sig = Buffer.from(input.signatureHex, 'hex');

  if (h.length !== 32) throw new Error(`buildQrBytes: contentHashHex must decode to 32 bytes, got ${h.length}.`);
  if (sig.length !== 64) throw new Error(`buildQrBytes: signatureHex must decode to 64 bytes, got ${sig.length}.`);

  const payload: QrPayload = { v: 1, iss: uuidToBytes(input.issuerId), doc: uuidToBytes(input.docId), h, sig };
  return encodeQrPayload(payload);
}

/** Renders the QR as a PNG buffer (for embedding directly in a PDF, no temp file). Same base64-text convention as generateQr.ts's renderQrPng. */
export async function renderQrPngBuffer(qrBytes: Buffer): Promise<Buffer> {
  const base64Text = qrBytes.toString('base64');
  // High error correction (30% recovery) rather than Medium — a QR that
  // has to survive a print, then a phone camera photo of that print (often
  // with some glare, slight blur, or an imperfect angle) benefits from the
  // extra redundancy far more than a QR only ever displayed on a screen
  // would. Higher resolution (768) also gives OpenCV's detector more real
  // pixels to work with once this gets scaled down to a physical page size.
  return QRCode.toBuffer(base64Text, { type: 'png', errorCorrectionLevel: 'H', margin: 3, width: 768 });
}
